modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/upgrade-aquatic/issues"
license = "https://github.com/team-abnormals/upgrade-aquatic/blob/main/LICENSE.txt"

[[mods]]
    modId = "upgrade_aquatic"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "SmellyModder, bageldotjpg, Cameron, five, SystemZee, Ocelot, Endergized"
    displayName = "Upgrade Aquatic"
    description = '''
    A mod that improves upon the content of 1.13 Update Aquatic.
    '''

[[dependencies.upgrade_aquatic]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.upgrade_aquatic]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.upgrade_aquatic]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.4,)"
    ordering = "AFTER"
    side = "BOTH"