modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/minecraftabnormals/Upgrade-Aquatic/issues"

[[mods]]
    modId="upgrade_aquatic"
    namespace="upgrade_aquatic"
    version="1.1"
    displayName="Upgrade Aquatic"
    authors="SmellyModder, Cameron, Five"
    description='''A mod that improves upon the content of 1.13 Update Aquatic.'''
    displayURL=""
    [[dependencies.upgrade_aquatic]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"